export const fullCourseSet = [
  {
    meeting_information: {
      lecture: {
        day: "LEC Mon, Wed, Fri",
        time: "04:30PM - 05:20PM",
        place: "MCLN, Room 102",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Tues",
        time: "02:30PM - 04:30PM (2022/12/13)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "PSYC*3250*01 (9093) Psychological Measurement",
    location: "Guelph",
    faculty: "J. Spence",
    available_capacity: "0 / 145",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "3250",
    section_number: "01",
    uid: "9093",
    course_name: "Psychological Measurement",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Tues, Thur",
        time: "04:00PM - 05:20PM",
        place: "ROZH, Room 103",
      },
      lab: {},
      seminar: {},
      exam: {},
    },
    term: "Fall 2022",
    status: "Open",
    section_name_and_title: "PSYC*3270*01 (9094) Cognitive Neuroscience",
    location: "Guelph",
    faculty: "N. Al-Aidroos",
    available_capacity: "12 / 192",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "3270",
    section_number: "01",
    uid: "9094",
    course_name: "Cognitive Neuroscience",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Wed",
        time: "11:30AM - 02:20PM",
        place: "MACN, Room 118",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Fri",
        time: "08:30AM - 10:30AM (2022/12/16)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "PSYC*4330*01 (9106) Adv Topics in I/O Psychology",
    location: "Guelph",
    faculty: "TBA TBA",
    available_capacity: "0 / 38",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "4330",
    section_number: "01",
    uid: "9106",
    course_name: "Adv Topics in I/O Psychology",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Tues, Thur",
        time: "02:30PM - 03:50PM",
        place: "ROZH, Room 101",
      },
      lab: {
        day: "LAB Mon",
        time: "11:30AM - 01:20PM",
        place: "REYN, Room 0002",
      },
      seminar: {},
      exam: {
        day: "EXAM Fri",
        time: "08:30AM - 10:30AM (2022/12/09)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "CIS*1300*0105 (7169) Programming",
    location: "Guelph",
    faculty: "R. Chaturvedi",
    available_capacity: "0 / 33",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "CIS",
    course_code: "1300",
    section_number: "0105",
    uid: "7169",
    course_name: "Programming",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Mon, Wed",
        time: "02:30PM - 03:50PM",
        place: "MINS, Room 103",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Tues",
        time: "08:30AM - 10:30AM (2022/12/06)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "FIN*3400*02 (7843) International Finance",
    location: "Guelph",
    faculty: "M. Li",
    available_capacity: "0 / 55",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "FIN",
    course_code: "3400",
    section_number: "02",
    uid: "7843",
    course_name: "International Finance",
  },
];

export const conflictingCourseSet = [
  {
    meeting_information: {
      lecture: {
        day: "LEC Mon, Wed, Fri",
        time: "04:30PM - 05:20PM",
        place: "MCLN, Room 102",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Tues",
        time: "02:30PM - 04:30PM (2022/12/13)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "PSYC*3250*01 (9093) Psychological Measurement",
    location: "Guelph",
    faculty: "J. Spence",
    available_capacity: "0 / 145",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "3250",
    section_number: "01",
    uid: "9093",
    course_name: "Psychological Measurement",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Tues, Thur",
        time: "02:30PM - 03:50PM",
        place: "ROZH, Room 103",
      },
      lab: {},
      seminar: {},
      exam: {},
    },
    term: "Fall 2022",
    status: "Open",
    section_name_and_title: "PSYC*3270*01 (9094) Cognitive Neuroscience",
    location: "Guelph",
    faculty: "N. Al-Aidroos",
    available_capacity: "12 / 192",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "3270",
    section_number: "01",
    uid: "9094",
    course_name: "Cognitive Neuroscience",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Wed",
        time: "11:30AM - 02:20PM",
        place: "MACN, Room 118",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Fri",
        time: "08:30AM - 10:30AM (2022/12/16)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "PSYC*4330*01 (9106) Adv Topics in I/O Psychology",
    location: "Guelph",
    faculty: "TBA TBA",
    available_capacity: "0 / 38",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "4330",
    section_number: "01",
    uid: "9106",
    course_name: "Adv Topics in I/O Psychology",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Tues, Thur",
        time: "02:30PM - 03:50PM",
        place: "ROZH, Room 101",
      },
      lab: {
        day: "LAB Mon",
        time: "11:30AM - 01:20PM",
        place: "REYN, Room 0002",
      },
      seminar: {},
      exam: {
        day: "EXAM Fri",
        time: "08:30AM - 10:30AM (2022/12/09)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "CIS*1300*0105 (7169) Programming",
    location: "Guelph",
    faculty: "R. Chaturvedi",
    available_capacity: "0 / 33",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "CIS",
    course_code: "1300",
    section_number: "0105",
    uid: "7169",
    course_name: "Programming",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Mon, Wed",
        time: "02:30PM - 03:50PM",
        place: "MINS, Room 103",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Tues",
        time: "08:30AM - 10:30AM (2022/12/06)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "FIN*3400*02 (7843) International Finance",
    location: "Guelph",
    faculty: "M. Li",
    available_capacity: "0 / 55",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "FIN",
    course_code: "3400",
    section_number: "02",
    uid: "7843",
    course_name: "International Finance",
  },
];

export const partialCourseSet = [
  {
    meeting_information: {
      lecture: {
        day: "LEC Mon, Wed, Fri",
        time: "04:30PM - 05:20PM",
        place: "MCLN, Room 102",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Tues",
        time: "02:30PM - 04:30PM (2022/12/13)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "PSYC*3250*01 (9093) Psychological Measurement",
    location: "Guelph",
    faculty: "J. Spence",
    available_capacity: "0 / 145",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "3250",
    section_number: "01",
    uid: "9093",
    course_name: "Psychological Measurement",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Tues, Thur",
        time: "04:00PM - 05:20PM",
        place: "ROZH, Room 103",
      },
      lab: {},
      seminar: {},
      exam: {},
    },
    term: "Fall 2022",
    status: "Open",
    section_name_and_title: "PSYC*3270*01 (9094) Cognitive Neuroscience",
    location: "Guelph",
    faculty: "N. Al-Aidroos",
    available_capacity: "12 / 192",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "3270",
    section_number: "01",
    uid: "9094",
    course_name: "Cognitive Neuroscience",
  },
  {
    meeting_information: {
      lecture: {
        day: "LEC Wed",
        time: "11:30AM - 02:20PM",
        place: "MACN, Room 118",
      },
      lab: {},
      seminar: {},
      exam: {
        day: "EXAM Fri",
        time: "08:30AM - 10:30AM (2022/12/16)",
        place: "Room TBA",
      },
    },
    term: "Fall 2022",
    status: "Closed",
    section_name_and_title: "PSYC*4330*01 (9106) Adv Topics in I/O Psychology",
    location: "Guelph",
    faculty: "TBA TBA",
    available_capacity: "0 / 38",
    credits: "0.50",
    ceus: "",
    academic_level: "Undergraduate",
    subject: "PSYC",
    course_code: "4330",
    section_number: "01",
    uid: "9106",
    course_name: "Adv Topics in I/O Psychology",
  },
];
